### ISSUE TITLE
Ordine del menu

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#1]
Sto provando il bot e l'unico consiglio che mi viene im nete é di cambiare l'ordine del menu con i comandi.

- [x] Mettere in cima gruppi e poi support (da cambiare in supporto)
- [x] feedback e info come ultimo
- [x] home come primo, prima di gruppi (fare anche un testo piú breve)

**Comment by Sav22999** [comment]
@Mte90  Va bene, l'ordine può essere modificato subito. Per il testo ti chiederei se hai idee e di inserire direttamente qui il testo con cui sostituire quello attuale :)

**Comment by Mte90** [comment]
```dove vengono trattate varie tematiche come aggiornamenti, novita', richiesta di informazione o supporto, e altro ancora. In poche parole il gruppo che accomuna tutti i volontari Mozilla Italia, a prescindere dal gruppo di appartenenza.```

per il comando home

**Comment by Sav22999** [comment]
Solved :)
