### ISSUE TITLE
Errore comando /prossimaCall

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/mozitahub_bot#14]
Digitando 
> /prossimaCall

viene restituito il messaggio
> Errore: comando non riconosciuto

**Comment by Sav22999** [comment]
@kitsunenosaraT, ho solo ora visto l'issue. Chiedo scusa se non ho risposto e risposto prima. Risolvo appena arrivo a casa. Grazid mille per il contributo!

**Comment by Sav22999** [comment]
@kitsunenosaraT perfetto. Errore corretto. Il comando esatto, ora,  è "prossimacall", non "prossimaCall" :)
