### ISSUE TITLE
Modificare nomi gestione mesi dell'anno

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/mozitahub_bot#17]
Per una gestione migliore del codice e per evitare ridondanze, meglio creare un array con i nomi dei mesi dell'anno e associare ad ogni elemento dell'array proprio il numero del mese dell'anno.
In questo modo, basterà estrapolare solamente il numero del mese e decrementarlo di 1.

Esempio di una possibile di una possibile implementazione in Java:
String[]mesi = {"Gennaio", "Febbraio", "Marzo"};
System.out.println("Data di oggi: " + Day.currentDay() + mesi[Day.currentMonth()-1] + Day.currentYear());

**Comment by Sav22999** [comment]
Miglioramento al codice apportato. Grazie mille per la collaborazione!
