### ISSUE TITLE
File di configurazione

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#19]
Stavo configurando i bot sulla mia vps ma mi sono reso conto che bisogna modificare i file e quindi non posso automatizzare l'aggiornamento dello stesso.
Meglio fare un file di configurazione dove si imposta il token, lo stesso file messo in `.gitignore` così può essere lasciato nella cartella e si può aggiornare il repository senza che ci siano errori.

**Comment by Sav22999** [comment]
Non ho capito bene ciò che vuoi dire (per mia ignoranza, probabilmente) :) puoi spiegarti meglio, per favore?

**Comment by Mte90** [comment]
Certo :-)
Di fare un file di configurazione tipo config.ini con il token come opzione.
Poi mettiamo in gitignore l'eccezione così il file non deve essere committato.
Di solito poi si fa un file config-example.ini.
Tipo https://github.com/CodeAtCode/freemius-suite vedi c'é il file config-example.ini

**Comment by Sav22999** [comment]
Ah, ok. Ora ho capito eheh. Chiedo venia.
In pratica imposta il token importandolo dal file "config.ini" (che è modificabile) giusto?

**Comment by Mte90** [comment]
si :-)
e poi facciamo che non viene committato

**Comment by Sav22999** [comment]
Perfetto! Va benissimo così! :)

Vuoi fare una pr direttamente tu? (dal momento che sei più famigliare con l'ambiente)

**Comment by Mte90** [comment]
ecco qua https://github.com/Sav22999/mozitahub_bot/pull/20

**Comment by Sav22999** [comment]
PR approvata. Chiudo l'issue
