### ISSUE TITLE
Aggiungere nei commenti a quale username corrisponde l'userid PER GLI ADMIN

### ISSUE THREAD

**Issue by Martinligabue** [MozillaItalia/mozitahub_bot#35]
mettere come commento i nomi degli id, per poterli gestire più semplicemente

**Comment by Mte90** [comment]
@Martinligabue puoi dare un po di contesto? Così non capisco bene il problema nello specifico.

**Comment by Martinligabue** [comment]
Se in futuro dovesse esserci bisogno di aggiornare la lista degli admin del bot farebbe comodo avere oltre all'ID anche il nome dell'utente, per non dover controllare gli id singolarmente

**Comment by Mte90** [comment]
I json non permettono commenti nel file quindi direi che non è fattibile.
Si fa prima a fare nel bot un comando che mostra i nick invece degli id.

**Comment by Martinligabue** [comment]
ah, peccato, il comando credo sia di troppo, se si potevano mettere commenti sarebbe stato abbastanza semplice, ma non c'è bisogno, credo, di fare un comando apposta

**Comment by Sav22999** [comment]
Credo che, comunque, Telegram non permetta di ottenere il nome utente solo avendo l'id.
