### ISSUE TITLE
Aggiungere stampa su file delle eccezioni

### ISSUE THREAD

**Issue by ilyasmg** [MozillaItalia/mozitahub_bot#41]
Al momento le eccezioni non vengono salvate sul file di log. Una soluzione potrebbe essere di implementare una funzione per stampare su file e poi chiamarla ogni volta che il programma finisce su un'eccezione ed anche per salvare i messaggi.

**Comment by Sav22999** [comment]
👍 concordo. Al momento è sufficiente assegnare il valore di "stampa" e viene automaticamente salvato su file
