### ISSUE TITLE
Aggiungere comando per inviare avvisi nel canale "News"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozitahub_bot#44]
Aggiungere un comando che permetta (agli admin!) di inviare avvisi sul canale "Mozilla Italia News", un'idea può essere:
- /admin mozitanews <MESSAGGIO> -> Invia il messaggio sul canale
- /admin moziranews preview <MESSAGGIO> -> Mostra un anteprima del messaggio sul bot, ma NON invia al canale

**Comment by GianluigiMemoli** [comment]
Per quanto riguarda un'eventuale eccezione durante la preview andrebbe utilizzata la Except23 o definita una nuova?

**Comment by Sav22999** [comment]
@GianluigiMemoli meglio definirne una nuova, così eventualmente sappiamo esattamente dove si è verificata l'eccezione (invece di avere 2 possibili casi).
Grazie per il tuo contributo

**Comment by GianluigiMemoli** [comment]
Così è stato fatto nella PR.
 Grazie a voi per la possibilità di contribuire 🚀

**Comment by Sav22999** [comment]
@GianluigiMemoli ok, dopo molti millenni ecco che rispondo.
Dunque, alcune modifiche:
- Se non sono presenti canali, mostra comunque avviso che "Inviato correttamente", invece deve mostrare "Non ci sono canali"
- Se non scrivo nulla (/admin mozitanews) non restituisce alcun messaggio di errore -> prevedere questo
- /admin mozitanews preview non funziona (invia il testo "preview"). Secondo me bisogna mettere prima "preview" e poi "mozitanews" -> "/admin preview mozitanews"
- Se scrivo "/admin canale HHH" non mostra messaggio di errore -> prevedere la condizione "else"

**Comment by GianluigiMemoli** [comment]
@Sav22999 L'avevo visto ma è stato un periodaccio per via della sessione e mi è sfuggito di mente. 
Vedo di rimediare entro una settimana, sono pure sviste che potevo evitare se avessi rifletutto sugli use case

**Comment by Sav22999** [comment]
@GianluigiMemoli Ok ok, nessun problema 😄 lavoraci quando hai tempo, senza fretta

**Comment by Sav22999** [comment]
Dal momento che @GianluigiMemoli non ha più risposto o continuato il lavoro, passo la palla a @dag7dev e gli assegno sia la PR #45, sia questo issue

**Comment by dag7dev** [comment]
Grazie @Sav22999 , va benissimo! Ci penso io!

**Comment by Mte90** [comment]
Direi che può riprendere il codice di @GianluigiMemoli e proseguire da li con le modifiche con una nuova pr per fare prima.

**Comment by Sav22999** [comment]
@Mte90 Sì, esatto, gli ho assetato anche la PR (come ho specificato nel mio commento precedente)
