### ISSUE TITLE
Pubblicare i tweet sul canale telegram

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#46]
Come da #44 sarebbe utile prendere i tweet originali (forse anche i retweet) da https://twitter.com/mozillaitalia e pubblicarli su telegram.

**Comment by dag7dev** [comment]
Gli dò un'occhiata questo pomeriggio!

**Comment by Mte90** [comment]
Il bot https://github.com/gambe-ro/lobsters-twitter-bot questo legge da un json e posta su twitter, a noi serve il contrario ma uno spunto non fa male.

**Comment by dag7dev** [comment]
Ci penso io!

**Comment by Sav22999** [comment]
Come da richiesta di @dag7dev gli assegno questo issue

**Comment by Mte90** [comment]
Già in funzione :-D

**Comment by dag7dev** [comment]
Promemoria per me:
- [ ] implementare https://github.com/franciscod/telegram-twitter-forwarder-bot eventualmente col multithreading 
- [ ] (opzionale) aggiungerlo come dipendenza di questa repo
