### ISSUE TITLE
Scaricare log del giorno corrente e del giorno precedente

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozitahub_bot#48]
Aggiungere:
`/admin scarica today`
`/admin scarica yesterday`

**Comment by ilyasmg** [comment]
come mai vuoi aggiungere queste funzionalita? assegnami pure :P

**Comment by Sav22999** [comment]
Diciamo che sono pigro e non mi va di inserire la data odierna manualmente :rofl:

**Comment by dag7dev** [comment]
> come mai vuoi aggiungere queste funzionalita? assegnami pure :P

mi raccomando quando lavori commenta sempre quello che fai e soprattutto scrivi /admin scarica today sopra la sezione dell'elif, cosi se dobbiamo metterci mano non abbiamo problemi e riusciamo a ritrovarla! ;)

Non dimenticartelo, è importante! @ilyasmg

**Comment by ilyasmg** [comment]
non ho capito sta parte: "scrivi /admin scarica today sopra la sezione dell'elif" Intendi dire di aggiungere un commento per far capire cosa fa quell'elif?

**Comment by dag7dev** [comment]
> non ho capito sta parte: "scrivi /admin scarica today sopra la sezione dell'elif" Intendi dire di aggiungere un commento per far capire cosa fa quell'elif?

Esattamente.
