### ISSUE TITLE
Creatore del bot

### ISSUE THREAD

**Issue by Martinligabue** [MozillaItalia/mozitahub_bot#5]
In genere nei bot è utile mettere l'username del creatore, in genere nelle /info e/o nell'/help (comando che manca in questo bot, da rendere redirect ad /azioni). So che ci son già tutti i link per i gruppi, ma un username diretto del creatore rende molto più facile a chi vuole segnalare bug contattare il dev.

**Comment by Sav22999** [comment]
Hai perfettamente ragione. Voglio comunicarti, tuttavia che il comando "/info" esiste, puoi accedere ad esso sia da "/azioni", sia digitando "/info".
Il nome del creatore (@Sav22999) non credo sia completamente necessario, poiché il bot è della comunità.
Colgo, tuttavia, la segnalazione per aggiungere (sempre a "/info") i nomi di tutti coloro che hanno dato una mano nella realizzazione, anche chi ha solamente segnalato qualcosa!

**Comment by Martinligabue** [comment]
sì, il comando /info esiste, ma manca /help, che è un comando comune, in alcuni client telegram anche messo fra quelli di default, io lo metterei comunque, per una maggiore compatibilità.
giusta la cosa dei nomi dei contributori, inoltre, propongo (non mi sembra di averlo visto), il link a github

**Comment by Sav22999** [comment]
Il link per GitHub mi sembra sì una buona idea, ma non direttamente nel bot. Cioè noi cerchiamo di avvicinare la gente a Mozilla Italia, una volta dentro, poi, li reindirizziamo nei vari progetti.

**Comment by Martinligabue** [comment]
ottimo

**Comment by Sav22999** [comment]
Si, per il comando /help effettivamente la mia prima idea era di metterlo, ma poi non sapevo **cosa** dovesse mostrare. In caso potremmo mostrare le informazioni (senza i contributori) a "help" e con il creatore e i vari contributori a "info".
Cosa ne pensi?

**Comment by Martinligabue** [comment]
sì, mi sembra una buona idea; in genere /help è usato per far vedere i comandi e/o cosa fa il bot, per cui mi sembra un buon compromesso quello che hai scritto

**Comment by Sav22999** [comment]
👍  altrimenti potremmo sostituire "azioni" con "help", meglio no?
