### ISSUE TITLE
Aggiungere link al tweet

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#53]
Ad oggi condividiamo il tweet ma non include il link al tweet.

Inoltre non si capisce molto se è un retweet in alcuni casi, forse aggiungere un `RT:` aiuterebbe.

**Comment by Sav22999** [comment]
Piuttosto che "RT" perché non scrivere proprio "Retweet"?

Per il link direi che possiamo mettere un bottone piuttosto che il semplice link, che dite?

**Comment by Mte90** [comment]
Per il testo mi va bene.
Per il pulsante questo lo sapete meglio voi che conoscete l'api di telegram

**Comment by Sav22999** [comment]
No, beh, è un qualcosa di grafico. Mettere il pulsante come per il bot: "Vedi su Twitter"

**Comment by dag7dev** [comment]
Son d'accordo per il pulsante cliccabile, son d'accordo anche per l'RT prima del tweet in caso di un retweet
