### ISSUE TITLE
Rimuovere pulsante "Visualizza tweet" perché causa un problema con i commenti nativi (non viene mostrato il pulsante per commentare)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozitahub_bot#55]
Al posto del pulsante "Visualizza tweet" si potrebbe usare la feature di Telegram (Instant View Button) oppure un semplice link `<a href="link_tweet">Visualizza tweet</a>`

**Comment by ilyasmg** [comment]
dalla documentazione di telepot non sembra esserci qualcosa per usare Instant View Button. Vado di link o lasciamo il pulsante?

**Comment by Sav22999** [comment]
@ilyasmg https://instantview.telegram.org/
