### ISSUE TITLE
"Prossimo meeting mensile" impostato manualmente invece che automatico

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozitahub_bot#58]
In questo modo si eviterebbe di dare date false.
Se non è stato impostato, per quel mese, mostrare "Non è presente alcun meeting mensile questo mese. Per ulteriori informazioni chiedi in Home"

**Comment by dag7dev** [comment]
In realtà l'abbiamo lasciato manuale perchè se avessimo avuto particolari esigenze l'avremmo modificato a dovere. Tipo quello di questo mese ancora non è stato aggiornato, per dirti

**Comment by Sav22999** [comment]
Infatti è quello il problema. Ora è automatico

**Comment by dag7dev** [comment]
> Infatti è quello il problema. Ora è automatico
> 

È manuale, abbiamo una variabile.
O non c'è più?

**Comment by Sav22999** [comment]
Non è mai stato manuale, sempre automatico

**Comment by dag7dev** [comment]
~Ci penso io!~

**Comment by Sav22999** [comment]
Non è stato ancora implementato 🙄
