### ISSUE TITLE
Remove user from bot notification when they block it

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozitahub_bot#70]
From the log:
```
Excep:08 -> ('Forbidden: bot was blocked by the user', 403, {'ok': False, 'error_code': 403, 'description': 'Forbidden: bot was blocked by the user'})
```

**Comment by Sav22999** [comment]
Users are already removed from the list

**Comment by Mte90** [comment]
Sorry the log wasn't cleaned and I didn't saw that.

**Comment by Sav22999** [comment]
No problem. In the log is printed that string (because it's actually an exception!), but after the bot analyses that exception and, in case, it removes from the "Avvisi" and "All users" lists
